// Room 1 - Message Room (spec name: Control Room)
// Dimension: Evaluation. Skill: Listening (Flyers Listening Part 1 style).
// DRAFT: waiting for teacher approval of language level.

export default {
  id: 'room1',
  order: 1,
  name: 'Message Room',
  specName: 'Control Room',
  dimension: 'Evaluation',
  skill: 'listening',
  icon: 'headphones',
  prize: { id: 'great-ears', name: 'Great Ears', icon: 'ear' },
  introAudio: 'r1_intro',
  intro: 'Meet the team. Listen and find the right person.',
  introEs: 'Conoce al equipo. Escucha y encuentra a la persona correcta.',
  helpCostsPoints: true,
  confidence: true,
  targetMinutes: 6,
  clue: {
    type: 'number',
    value: '450',
    label: '450',
    sourceItem: 'r1_q3',
    evidence: 'four hundred and fifty',
  },
  items: [
    {
      id: 'r1_q1',
      type: 'choice',
      skill: 'listening',
      audio: 'r1_q1',
      instruction: 'Listen. Which person is Sarah?',
      instructionEs: 'Escucha. ¿Qué persona es Sarah?',
      layout: 'pictures',
      options: [
        { id: 'a', image: 'r1_sarah_a', alt: 'A woman with long curly hair and glasses. She is holding a torch.' },
        { id: 'b', image: 'r1_sarah_b', alt: 'A woman with long straight hair and glasses. She is holding a torch.' },
        { id: 'c', image: 'r1_sarah_c', alt: 'A woman with long curly hair. She has not got glasses. She is holding a key.' },
      ],
      answer: 'a',
      why: 'Yes! Sarah has got curly hair and glasses. She is holding a torch.',
      hints: [
        'Listen again. What is Sarah\'s hair like?',
        'Sarah is wearing something. Look at the eyes.',
        'Read the words of the message. Then look at the pictures again.',
      ],
      showTranscriptOnHint: 3,
      words: ['engineer', 'curly', 'glasses', 'torch', 'hold'],
    },
    {
      id: 'r1_q2',
      type: 'choice',
      skill: 'listening',
      audio: 'r1_q2',
      instruction: 'Listen. Which person is Richard?',
      instructionEs: 'Escucha. ¿Qué persona es Richard?',
      layout: 'pictures',
      options: [
        { id: 'a', image: 'r1_richard_a', alt: 'A man with a short beard. He has not got a moustache. He is sitting next to the window.' },
        { id: 'b', image: 'r1_richard_b', alt: 'A man with a short beard and a moustache. He is sitting next to the window.' },
        { id: 'c', image: 'r1_richard_c', alt: 'A man with a short beard. He has not got a moustache. He is standing next to the door.' },
      ],
      answer: 'a',
      why: 'Yes! Richard has got a beard, but not a moustache. He is sitting next to the window.',
      hints: [
        'Listen again. Has Richard got a moustache?',
        'Is Richard sitting or standing? Where is he?',
        'Read the words of the message. Then look at the pictures again.',
      ],
      showTranscriptOnHint: 3,
      words: ['pilot', 'beard', 'moustache', 'window', 'next to'],
    },
    {
      id: 'r1_q3',
      type: 'choice',
      skill: 'listening',
      audio: 'r1_q3',
      instruction: 'Listen. What number is on William\'s box?',
      instructionEs: 'Escucha. ¿Qué número tiene la caja de William?',
      layout: 'big-text',
      options: [
        { id: 'a', text: '450' },
        { id: 'b', text: '415' },
        { id: 'c', text: '540' },
      ],
      answer: 'a',
      why: 'Yes! Four hundred and fifty is 450.',
      hints: [
        'Listen again. Listen to William.',
        'The number starts with "four hundred".',
        'Read the words of the message. Then look at the numbers again.',
      ],
      showTranscriptOnHint: 3,
      words: ['mechanic', 'metal', 'box', 'hundred', 'youngest'],
    },
  ],
};
