// Interface text (buttons, instructions, messages). English, A2 Flyers list only.
// {n}, {total} etc. are filled in by the game.

export default {
  title: 'Radio Silence on Space Station Alpha',
  skipLink: 'Go to the game',
  // start
  welcomeTitle: 'Hello, Cadet!',
  welcomeSteps: [
    { icon: 'headphones', text: 'Listen to the messages.' },
    { icon: 'piece', text: 'Find a secret piece in every room.' },
    { icon: 'radio', text: 'Repair the radio in the Radio Room.' },
  ],
  timeNote: 'You have got 30 minutes. Don\'t worry: you can always finish.',
  helpNote: 'Need help? Ask Pip.',
  listenHelen: 'Listen to Helen',
  launch: 'Let\'s go',
  start: 'Start',
  resume: 'Go back to my game',
  newGame: 'Start a new game',
  // settings
  settings: 'Configuration',
  settingsTitle: 'Configuration',
  textSize: 'Text',
  sizes: ['Big', 'Bigger', 'Very big'],
  lineSpace: 'Space between lines',
  lineOptions: ['Small', 'Big'],
  font: 'Letters',
  contrast: 'Strong colours',
  sounds: 'Game sounds',
  calm: 'Quiet clock',
  calmHelp: 'No numbers. The clock is a line.',
  spanish: 'Ayuda en español',
  on: 'On',
  off: 'Off',
  close: 'Close',
  // map
  mapTitle: 'Station map',
  mapHelp: 'Look at the yellow part. Then choose that room.',
  go: 'Go',
  finished: 'Finished',
  nextRoom: 'Next',
  statusClosed: 'Closed',
  statusOpen: 'Open',
  piecesFound: '{n} of 5 secret pieces',
  myPieces: 'My secret pieces',
  findAllFirst: 'Find all 5 secret pieces first.',
  // timer
  time: 'Time',
  timeLeft: '{n} minutes',
  timeUpTitle: 'The clock stopped.',
  timeUpText: 'Don\'t worry! You can still repair the radio. Take your time.',
  practice: 'Practice time',
  ok: 'OK',
  // items
  answer: 'Answer',
  next: 'Next',
  tryAgain: 'Try again',
  help: 'Help, Pip!',
  pipSays: 'Pip says:',
  right: 'Right!',
  notYet: 'Not yet. Try again!',
  questionOf: '{n} of {total}',
  // audio
  play: 'Play',
  listenAgain: 'Listen again',
  playsLeft: 'You can listen {n} more times.',
  oneLeft: 'You can listen one more time.',
  noPlaysLeft: 'You listened two times. You can read the words.',
  showWords: 'Show the words',
  hideWords: 'Hide the words',
  loading: 'Wait, please ...',
  audioMissing: 'Sorry, there is no sound here. Read the words.',
  picture: 'Picture',
  // confidence
  howSure: 'How sure are you?',
  sure: ['Not sure', 'Quite sure', 'Very sure'],
  sureRightHigh: 'You were very sure, and you were right! Great!',
  sureRightLow: 'You were right! Next time, you can be more sure.',
  sureWrongHigh: 'You were very sure, but it isn\'t right. Listen again carefully.',
  sureWrongLow: 'You weren\'t sure, and that\'s OK. Let\'s listen again.',
  // room summary
  summaryTitle: 'Room finished!',
  foundPiece: 'You found a secret piece!',
  stars: 'Stars',
  helpUsed: 'Help from Pip: {n}',
  wordsPractised: 'Words you practised',
  prize: 'Prize',
  fastStar: 'Fast star!',
  score: 'Score',
  backToMap: 'Go to the map',
  streak: '{n} right answers, one after the other!',
  // room 2
  chooseRead: 'How do you want to read?',
  lookHere: 'Look here',
  // room 3
  choosePath: 'Choose your path',
  changePath: 'Change path',
  wordBox: 'Word box',
  // room 4
  tapWords: 'Choose the words one by one.',
  yourSentence: 'Your sentence',
  clear: 'Start again',
  // postcard
  wordCount: 'Words: {n}',
  boxWordsUsed: 'Words from the box: {n}',
  // final
  choosePiece: 'Choose a piece',
  radioWorking: 'The radio is working!',
  // end
  endTitle: 'You repaired the radio!',
  totalScore: 'Score',
  yourPrizes: 'Your prizes',
  skills: { listening: 'Listening', reading: 'Reading', writing: 'Writing' },
  skillLine: '{right} of {total} right the first time',
  wordsToReview: 'Words to look at again',
  noWordsToReview: 'Great! You haven\'t got any words to look at again.',
  playAgain: 'Play again',
  pieceTypes: { number: 'number', word: 'word', symbol: 'picture', colour: 'colour', shape: 'shape' },
};
