// "Ayuda en español": Spanish for instructions and buttons ONLY.
// Never add Spanish for test items, answer options or vocabulary under test.

export default {
  welcomeTitle: '¡Hola, Cadete!',
  welcomeSteps: [
    { icon: 'headphones', text: 'Escucha los mensajes.' },
    { icon: 'piece', text: 'Encuentra una pieza secreta en cada sala.' },
    { icon: 'radio', text: 'Repara la radio en la Sala de Radio.' },
  ],
  timeNote: 'Tienes 30 minutos. No te preocupes: siempre puedes terminar.',
  helpNote: '¿Necesitas ayuda? Pregunta a Pip.',
  listenHelen: 'Escuchar a Helen',
  start: 'Empezar',
  resume: 'Volver a mi partida',
  newGame: 'Empezar una partida nueva',
  settings: 'Configuración',
  settingsTitle: 'Configuración',
  textSize: 'Tamaño del texto',
  sizes: ['Grande', 'Más grande', 'Muy grande'],
  lineSpace: 'Espacio entre líneas',
  lineOptions: ['Pequeño', 'Grande'],
  font: 'Tipo de letra',
  contrast: 'Colores fuertes (alto contraste)',
  sounds: 'Sonidos del juego',
  calm: 'Reloj tranquilo',
  calmHelp: 'Sin números. El reloj es una barra.',
  spanish: 'Ayuda en español',
  on: 'Sí',
  off: 'No',
  close: 'Cerrar',
  mapTitle: 'Mapa de la estación',
  go: 'Ir',
  finished: 'Terminada',
  nextRoom: 'Siguiente',
  statusClosed: 'Cerrado',
  statusOpen: 'Abierto',
  piecesFound: '{n} de 5 piezas secretas',
  myPieces: 'Mis piezas secretas',
  findAllFirst: 'Primero encuentra las 5 piezas secretas.',
  time: 'Tiempo',
  timeLeft: '{n} minutos',
  timeUpTitle: 'El reloj se paró.',
  timeUpText: '¡No te preocupes! Todavía puedes reparar la radio. Tómate tu tiempo.',
  practice: 'Modo práctica',
  ok: 'De acuerdo',
  answer: 'Responder',
  next: 'Siguiente',
  tryAgain: 'Inténtalo otra vez',
  help: '¡Ayuda, Pip!',
  pipSays: 'Pip dice:',
  questionOf: '{n} de {total}',
  play: 'Reproducir',
  listenAgain: 'Escuchar otra vez',
  playsLeft: 'Puedes escuchar {n} veces más.',
  oneLeft: 'Puedes escuchar una vez más.',
  noPlaysLeft: 'Ya escuchaste dos veces. Puedes leer las palabras.',
  showWords: 'Mostrar el texto',
  hideWords: 'Ocultar el texto',
  loading: 'Espera, por favor...',
  audioMissing: 'Lo sentimos, aquí no hay sonido. Lee el texto.',
  howSure: '¿Qué tan seguro/a estás?',
  sure: ['No estoy seguro/a', 'Bastante seguro/a', 'Muy seguro/a'],
  summaryTitle: '¡Sala terminada!',
  foundPiece: '¡Encontraste una pieza secreta!',
  stars: 'Estrellas',
  helpUsed: 'Ayudas de Pip: {n}',
  wordsPractised: 'Palabras que practicaste',
  prize: 'Premio',
  score: 'Puntos',
  backToMap: 'Ir al mapa',
  chooseRead: '¿Cómo quieres leer?',
  choosePath: 'Elige tu camino',
  changePath: 'Cambiar de camino',
  wordBox: 'Caja de palabras',
  tapWords: 'Elige las palabras en orden.',
  yourSentence: 'Tu oración',
  clear: 'Empezar otra vez',
  choosePiece: 'Elige una pieza',
  endTitle: '¡Reparaste la radio!',
  totalScore: 'Puntos',
  yourPrizes: 'Tus premios',
  wordsToReview: 'Palabras para repasar',
  playAgain: 'Jugar otra vez',
};
